export default {
  type: {
    "basis": "curveBasis",
    "basis-closed": "curveBasisClosed",
    "basis-open": "curveBasisOpen",
    "bundle": "curveBundle",
    "cardinal": "curveCardinal",
    "cardinal-closed": "curveCardinalClosed",
    "cardinal-open": "curveCardinalOpen",
    "catmull-rom": "curveCatmullRom",
    "catmull-rom-closed": "curveCatmullRomClosed",
    "catmull-rom-open": "curveCatmullRomOpen",
    "linear": "curveLinear",
    "linear-closed": "curveLinearClosed",
    "monotone-x": "curveMonotoneX",
    "monotone-y": "curveMonotoneY",
    "natural": "curveNatural",
    "step": "curveStep",
    "step-after": "curveStepAfter",
    "step-before": "curveStepBefore",
  } as const,
};
